### ISSUE TITLE
list 3 algorithms a link or problem description

### ISSUE THREAD

**Issue by calvinsettachatgul** [calvinsettachatgul/cara#5]
from codewars
leet code
hackerrank
cracking the coding interview

**Comment by Ramsanine** [comment]
Hey Calvin, you just want me to link 3 algorithm problems from any of these sites?

**Comment by calvinsettachatgul** [comment]
Yes that would be good or you can start files in the algorithm folder with a link and description. Thanks that would be awesome.  If you don't have a good GitHub workflow down then we can go over it. 



Calvin Settachatgul
5102208405

**Comment by calvinsettachatgul** [comment]
here im going to check out a branch and create 3 files
the branch is 
feature-5-list-3-algo
I'll create a pull request for it

**Comment by calvinsettachatgul** [comment]
I'm going to create a PR for adding 3 files for algorithms that I found.  In the code files I have a comment that you have to create a test file in the test directory. Tests have to be written to get some practice.  We can switch on implementation and writing tests during our meetings.

I've included you on a review to approve the PR.  If any of this work flow does not make sense or you think it's too much to do then let me know.  I'm trying to simulate a work like environment with issues and implementation of the solution.

**Comment by calvinsettachatgul** [comment]
You can view the open issues for the algorithms project here
https://github.com/calvinsettachatgul/cara/projects/2

**Comment by calvinsettachatgul** [comment]
I'm going to take myself off this issue. If you want you can add your problems.

**Comment by Ramsanine** [comment]
Hey Calvin, I am a little confused about how I add the algorithm links.  Do I just add them here in the comments?  Or is there a place I put them on the cloud?  Here are three random problems I chose from the sites listed above.

https://leetcode.com/problems/two-sum/

https://www.hackerrank.com/challenges/plus-minus/problem

https://www.codewars.com/kata/statistics-for-an-athletic-association/train/python

**Comment by calvinsettachatgul** [comment]
You can create files for them in algorithms. with comments is  the description of the problem. Name the file after the function we will implement. 



Calvin Settachatgul
5102208405
