### ISSUE TITLE
Go through a github tutorial

### ISSUE THREAD

**Issue by Ramsanine** [calvinsettachatgul/cara#9]
Go through one github tutorial to get a better idea of what you are doing with github.  Issues, Pull requests, branches and closing issues.  And try some of the processes you learn in github.

**Comment by calvinsettachatgul** [comment]
Where are the GitHub tutorials?

**Comment by Ramsanine** [comment]
Hey Calvin,  I have not found a tutorial but yes,  I found the guides just now that you mentioned above.  
https://guides.github.com/
Yes, that is exactly what I had in mind.  Maybe we can just take our time and do a couple of these guides.  I thought it would help.  Especially for me since I was confused on what to do on some of the issues so I wanted to get a better understanding.

**Comment by Ramsanine** [comment]
Hey,  I just went through the Hello World guide and its starting make a lot more sense with a little hands on tutorial/guide.  I don't think you really need to go through that one.  I think you are too advanced for that one.

**Comment by calvinsettachatgul** [comment]
@Ramsanine I'm not sure what I should do for this can we close this issue? Unless you have a tutorial to go through together

**Comment by calvinsettachatgul** [comment]
closing for not actionable
